### ISSUE TITLE
Exception when running cache clear.

### ISSUE THREAD

**Issue by geertjanknapen1** [swayok/alternative-laravel-cache#57]
I've recently updated my Laravel 10 project to Laravel 11. After this, my website keeps timing out. The log shows the following problems. Any help would be greatly appreciated.

```shell
[2024-10-08 15:20:27] dev.ERROR: Exception thrown when executing "clear".  {"exception":"[object] (Cache\\Adapter\\Common\\Exception\\CachePoolException(code: 0): Exception thrown when executing \"clear\".  at /usr/share/nginx/html/vendor/cache/adapter-common/AbstractCachePool.php:338)
[stacktrace]
#0 /usr/share/nginx/html/vendor/cache/adapter-common/AbstractCachePool.php(178): Cache\\Adapter\\Common\\AbstractCachePool->handleException()
#1 /usr/share/nginx/html/vendor/swayok/alternative-laravel-cache/AlternativeLaravelCache/Core/AlternativeCacheStore.php(285): Cache\\Adapter\\Common\\AbstractCachePool->clear()
#2 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(793): AlternativeLaravelCache\\Core\\AlternativeCacheStore->flush()
#3 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/Console/ClearCommand.php(69): Illuminate\\Cache\\Repository->__call()
#4 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Cache\\Console\\ClearCommand->handle()
#5 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#9 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#10 /usr/share/nginx/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#11 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#12 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
#13 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#14 /usr/share/nginx/html/vendor/statamic/cms/src/Console/Commands/Install.php(104): Illuminate\\Console\\Command->call()
#15 /usr/share/nginx/html/vendor/statamic/cms/src/Console/Commands/Install.php(43): Statamic\\Console\\Commands\\Install->clearCache()
#16 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Statamic\\Console\\Commands\\Install->handle()
#17 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#21 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#22 /usr/share/nginx/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#23 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#24 /usr/share/nginx/html/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#25 /usr/share/nginx/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#26 /usr/share/nginx/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#27 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
#28 /usr/share/nginx/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#29 {main}

[previous exception] [object] (League\\Flysystem\\UnableToDeleteDirectory(code: 0): Unable to delete directory located at: cache. at /usr/share/nginx/html/vendor/league/flysystem/src/UnableToDeleteDirectory.php:27)
[stacktrace]
#0 /usr/share/nginx/html/vendor/league/flysystem-local/LocalFilesystemAdapter.php(172): League\\Flysystem\\UnableToDeleteDirectory::atLocation()
#1 /usr/share/nginx/html/vendor/league/flysystem/src/Filesystem.php(91): League\\Flysystem\\Local\\LocalFilesystemAdapter->deleteDirectory()
#2 /usr/share/nginx/html/vendor/swayok/cache-filesystem-adapter/FilesystemCachePool.php(98): League\\Flysystem\\Filesystem->deleteDirectory()
#3 /usr/share/nginx/html/vendor/cache/adapter-common/AbstractCachePool.php(176): Cache\\Adapter\\Filesystem\\FilesystemCachePool->clearAllObjectsFromCache()
#4 /usr/share/nginx/html/vendor/swayok/alternative-laravel-cache/AlternativeLaravelCache/Core/AlternativeCacheStore.php(285): Cache\\Adapter\\Common\\AbstractCachePool->clear()
#5 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(793): AlternativeLaravelCache\\Core\\AlternativeCacheStore->flush()
#6 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Cache/Console/ClearCommand.php(69): Illuminate\\Cache\\Repository->__call()
#7 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Cache\\Console\\ClearCommand->handle()
#8 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#12 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#13 /usr/share/nginx/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#14 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#15 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
#16 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#17 /usr/share/nginx/html/vendor/statamic/cms/src/Console/Commands/Install.php(104): Illuminate\\Console\\Command->call()
#18 /usr/share/nginx/html/vendor/statamic/cms/src/Console/Commands/Install.php(43): Statamic\\Console\\Commands\\Install->clearCache()
#19 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Statamic\\Console\\Commands\\Install->handle()
#20 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#22 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#23 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#24 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#25 /usr/share/nginx/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#26 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#27 /usr/share/nginx/html/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#28 /usr/share/nginx/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#29 /usr/share/nginx/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#30 /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
#31 /usr/share/nginx/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"}
```

**Comment by swayok** [comment]
Problem is here: Unable to delete directory located at: cache
It seems like cache directory cannot be deleted because of lack of permissions or something like that.

**Comment by geertjanknapen1** [comment]
> Problem is here: Unable to delete directory located at: cache It seems like cache directory cannot be deleted because of lack of permissions or something like that.

Yeah, that's why I thought too. But I've checked permissions, even delete the directories myself and re-created them. Same thing happens. So that does not seem to be the actual cause of the problem.

There are also no stacktraces with the PHP timeouts, so this is the only thing I have to go off.

**Comment by swayok** [comment]
`cache:clear` actually should not cause timeout. Try disabling cache in `.env`. 

There is a possibility that your console user who runs `atrisan cache:clear` is different from the www user (usually www-data) and not included in `www-data` group. This will trigger the permission denial on delete. 

There are configs for file and folder permissions, use 0777 for folder and 0666 for files and check if problem is fixed:
```
'stores' => [
    'file' => [
        'driver' => 'file',
        'path' => storage_path('framework/cache/data'),
        'permissions' => [
            'file' => [
                'public' => 0666,
            ],
            'dir' => [
                'public' => 0777,
            ],
        ]
    ],
],
```

If you can use Redis - switch to Redis. File-based cache is not the best solution.

**Comment by geertjanknapen1** [comment]
Thanks for the quick replies!
It seems that the problem is not in the cache, even though everything seemed to point at it.

Thanks though!
